[tool.poetry]
name = "anim4u-py"
version = "0.0.0-beta"
description = "A Python CLI for download anime"

[tool.poetry.dependencies]
iamstarcode-anim4u_py = "*"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"